test: &test
  stage: test
  language: python
  install:
    - ./scripts/install-talib.sh
    - pip install .[full,cov]
  script:
    - export NUMBA_BOUNDSCHECK=1
    - pytest tests/
    - export NUMBA_DISABLE_JIT=1
    - pytest --cov=vectorbt tests/
  after_success:
    - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then codecov; fi

jobs:
  include:
    - <<: *test
      python: 3.6
    - <<: *test
      python: 3.7
    - <<: *test
      python: 3.8
    - <<: *test
      python: 3.9
    - stage: deploy-pypi
      language: python
      python: "3.6"
      script: skip
      deploy:
        - provider: pypi
          skip_existing: true
          username: "__token__"
          password:
            secure: k+1Rs3iUivAanltzMx+SrMoXOv6dvsY2kxzCbLUN2vD3umaM2b6UECbnGnYEb3Y0Mmj0mxu37k9znvOSvbLsXYTZqk7KBFy9XPI+b6tSj7u7O+GlTAZta6VixnsZWlyuwUIbPTcNd82HqfLbhU/pOo9ZNzWDhg37LASKrIz//orJoJjYGfAEDU9u8BA7k7pcCcGp5N1a7O5Ab5Ecko5Q993oyxi+ernU/HBmvW6XZHKwub3TFXzUJBMeiCMVUtRdlEEteG32ydHcX2F+gKjLRQNE0hXicqUERyQ65ceCJlks+pgpCsvu9snR4MniKTfolZrrK4b8BRQ1S7OEk32qZ9ldOcjpVCruEyz8PxEGuAVU7J817tn6QjZdA5EBWg3RXnxZAcqyyNtFd1KK6hMfvUmQkgAeyG8UGP8XP9vmf8bqJnYAPhwCAavCcc6SHM72MF8WIOb5Lbgw39toFwNgPJAZUCWBRA7In2vP9Z1WC7HK3bcRmdIjZVAs2N55yFsQHOw6DO0sJwjmFyxgsG92K0hZ4rftRi2eRkq8JB6ZliFgUfjUlZrc8jTMB0pSDp2zzZaK/tj1lKFZ72f/jeS08B8g+34wNfhvfH8BW4fLkne2YuUKV9sPfaCPLUzN3odyVRLrpFetrwabBR7F/fg5N6VzpsxbUguQNXDBURrHlUo=
          on:
            branch: master
    - stage: deploy-pages
      language: python
      python: "3.6"
      install:
        - ./scripts/install-talib.sh
        - pip install .[full,docs]
      script:
        - pdoc --html --force --output-dir docs vectorbt --template-dir docs/templates
        - rm -rf !(docs)
        - mv docs/vectorbt/* docs
        - rmdir docs/vectorbt
        - mv docs/site/* .
      deploy:
        - provider: pages
          skip_cleanup: true
          github_token: "$GITHUB_TOKEN"
          keep_history: true
          on:
            branch: master
    - stage: deploy-docker
      language: ruby
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t polakowo/vectorbt . --build-arg FULL=
        - ./scripts/docker-push.sh "polakowo/vectorbt" "$(cat vectorbt/_version.py | cut -d '"' -f 2)"
        - docker build -t polakowo/vectorbt-full . --build-arg FULL=yes --build-arg TEST=yes
        - ./scripts/docker-push.sh "polakowo/vectorbt-full" "$(cat vectorbt/_version.py | cut -d '"' -f 2)"

stages:
  - name: test
    if: (type = pull_request) OR (commit_message =~ /(\[ci test\]|\[ci deploy\])/)
  - name: deploy-pypi
    if: (type != pull_request) AND (commit_message =~ /(\[ci deploy-pypi\]|\[ci deploy\])/)
  - name: deploy-pages
    if: (type != pull_request) AND (commit_message =~ /(\[ci deploy-pages\]|\[ci deploy\])/)
  - name: deploy-docker
    if: (type != pull_request) AND (commit_message =~ /(\[ci deploy-docker\]|\[ci deploy\])/)
branches:
  only:
  - master